import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-drayage-chassis-invoice-recovery",
  "engine": "recovery",
  "title": "Drayage & Chassis Invoice Recovery",
  "shortTitle": "Drayage and Chassis Invoice Recovery",
  "tagline": "Quantify, recover, and prevent financial leakage through drayage & chassis invoice recovery",
  "industry": "Port Drayage Spend Recovery",
  "uiPort": 4607,
  "apiPort": 5607,
  "accent": "#15803d",
  "currency": "USD",
  "primaryOutcome": "Drayage & Chassis Invoice Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect drayage contracts, containers, bookings, port and ramp events, appointments, chassis usage, flips, splits, pre-pulls, storage, permits, tolls, invoices, and credits in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "billedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Drayage Billed Amount",
    "expectedLabel": "Event-Supported Amount",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Drayage & Chassis Invoice Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("drayage-contract-library","DCI01","Drayage contract library","Execute drayage contract library using drayage contracts, containers, bookings, port and ramp events, appointments, chassis usage, flips, splits, pre-pulls, storage, permits, tolls, invoices, and credits.","Produce a governed drayage contract library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Drayage Carrier / Container","text","Drayage Carrier / Container · Standard Case"],["caseReference","Drayage contract library Reference","text","DCI01-2026-001"],["billedAmount","Drayage Billed Amount","currency",716000],["supportedAmount","Event-Supported Amount","currency",615760],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Drayage contract library case","Container booking registry case","Port rail event ingestion case","Appointment evidence case","Base drayage calculation case"]}),
feature("container-booking-registry","DCI02","Container booking registry","Execute container booking registry using drayage contracts, containers, bookings, port and ramp events, appointments, chassis usage, flips, splits, pre-pulls, storage, permits, tolls, invoices, and credits.","Produce a governed container booking registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Drayage Carrier / Container","text","Drayage Carrier / Container · Standard Case"],["caseReference","Container booking registry Reference","text","DCI02-2026-001"],["billedAmount","Drayage Billed Amount","currency",716000],["supportedAmount","Event-Supported Amount","currency",615760],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Drayage contract library case","Container booking registry case","Port rail event ingestion case","Appointment evidence case","Base drayage calculation case"]}),
feature("port-rail-event-ingestion","DCI03","Port rail event ingestion","Execute port rail event ingestion using drayage contracts, containers, bookings, port and ramp events, appointments, chassis usage, flips, splits, pre-pulls, storage, permits, tolls, invoices, and credits.","Produce a governed port rail event ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Drayage Carrier / Container","text","Drayage Carrier / Container · Standard Case"],["caseReference","Port rail event ingestion Reference","text","DCI03-2026-001"],["billedAmount","Drayage Billed Amount","currency",716000],["supportedAmount","Event-Supported Amount","currency",615760],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Drayage contract library case","Container booking registry case","Port rail event ingestion case","Appointment evidence case","Base drayage calculation case"]}),
feature("appointment-evidence","DCI04","Appointment evidence","Execute appointment evidence using drayage contracts, containers, bookings, port and ramp events, appointments, chassis usage, flips, splits, pre-pulls, storage, permits, tolls, invoices, and credits.","Produce a governed appointment evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Drayage Carrier / Container","text","Drayage Carrier / Container · Standard Case"],["caseReference","Appointment evidence Reference","text","DCI04-2026-001"],["billedAmount","Drayage Billed Amount","currency",716000],["supportedAmount","Event-Supported Amount","currency",615760],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Drayage contract library case","Container booking registry case","Port rail event ingestion case","Appointment evidence case","Base drayage calculation case"]}),
feature("base-drayage-calculation","DCI05","Base drayage calculation","Execute base drayage calculation using drayage contracts, containers, bookings, port and ramp events, appointments, chassis usage, flips, splits, pre-pulls, storage, permits, tolls, invoices, and credits.","Produce a governed base drayage calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Drayage Carrier / Container","text","Drayage Carrier / Container · Standard Case"],["caseReference","Base drayage calculation Reference","text","DCI05-2026-001"],["billedAmount","Drayage Billed Amount","currency",716000],["supportedAmount","Event-Supported Amount","currency",615760],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Drayage contract library case","Container booking registry case","Port rail event ingestion case","Appointment evidence case","Base drayage calculation case"]}),
feature("chassis-day-reconciliation","DCI06","Chassis day reconciliation","Execute chassis day reconciliation using drayage contracts, containers, bookings, port and ramp events, appointments, chassis usage, flips, splits, pre-pulls, storage, permits, tolls, invoices, and credits.","Produce a governed chassis day reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Drayage Carrier / Container","text","Drayage Carrier / Container · Standard Case"],["caseReference","Chassis day reconciliation Reference","text","DCI06-2026-001"],["billedAmount","Drayage Billed Amount","currency",716000],["supportedAmount","Event-Supported Amount","currency",615760],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Drayage contract library case","Container booking registry case","Port rail event ingestion case","Appointment evidence case","Base drayage calculation case"]}),
feature("split-charge-validation","DCI07","Split charge validation","Execute split charge validation using drayage contracts, containers, bookings, port and ramp events, appointments, chassis usage, flips, splits, pre-pulls, storage, permits, tolls, invoices, and credits.","Produce a governed split charge validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Drayage Carrier / Container","text","Drayage Carrier / Container · Standard Case"],["caseReference","Split charge validation Reference","text","DCI07-2026-001"],["billedAmount","Drayage Billed Amount","currency",716000],["supportedAmount","Event-Supported Amount","currency",615760],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Drayage contract library case","Container booking registry case","Port rail event ingestion case","Appointment evidence case","Base drayage calculation case"]}),
feature("flip-charge-validation","DCI08","Flip charge validation","Execute flip charge validation using drayage contracts, containers, bookings, port and ramp events, appointments, chassis usage, flips, splits, pre-pulls, storage, permits, tolls, invoices, and credits.","Produce a governed flip charge validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Drayage Carrier / Container","text","Drayage Carrier / Container · Standard Case"],["caseReference","Flip charge validation Reference","text","DCI08-2026-001"],["billedAmount","Drayage Billed Amount","currency",716000],["supportedAmount","Event-Supported Amount","currency",615760],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Drayage contract library case","Container booking registry case","Port rail event ingestion case","Appointment evidence case","Base drayage calculation case"]}),
feature("pre-pull-audit","DCI09","Pre-pull audit","Execute pre-pull audit using drayage contracts, containers, bookings, port and ramp events, appointments, chassis usage, flips, splits, pre-pulls, storage, permits, tolls, invoices, and credits.","Produce a governed pre-pull audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Drayage Carrier / Container","text","Drayage Carrier / Container · Standard Case"],["caseReference","Pre-pull audit Reference","text","DCI09-2026-001"],["billedAmount","Drayage Billed Amount","currency",716000],["supportedAmount","Event-Supported Amount","currency",615760],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Drayage contract library case","Container booking registry case","Port rail event ingestion case","Appointment evidence case","Base drayage calculation case"]}),
feature("storage-yard-charge-control","DCI10","Storage yard charge control","Execute storage yard charge control using drayage contracts, containers, bookings, port and ramp events, appointments, chassis usage, flips, splits, pre-pulls, storage, permits, tolls, invoices, and credits.","Produce a governed storage yard charge control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Drayage Carrier / Container","text","Drayage Carrier / Container · Standard Case"],["caseReference","Storage yard charge control Reference","text","DCI10-2026-001"],["billedAmount","Drayage Billed Amount","currency",716000],["supportedAmount","Event-Supported Amount","currency",615760],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Drayage contract library case","Container booking registry case","Port rail event ingestion case","Appointment evidence case","Base drayage calculation case"]}),
feature("overweight-permit-validation","DCI11","Overweight permit validation","Execute overweight permit validation using drayage contracts, containers, bookings, port and ramp events, appointments, chassis usage, flips, splits, pre-pulls, storage, permits, tolls, invoices, and credits.","Produce a governed overweight permit validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Drayage Carrier / Container","text","Drayage Carrier / Container · Standard Case"],["caseReference","Overweight permit validation Reference","text","DCI11-2026-001"],["billedAmount","Drayage Billed Amount","currency",716000],["supportedAmount","Event-Supported Amount","currency",615760],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Drayage contract library case","Container booking registry case","Port rail event ingestion case","Appointment evidence case","Base drayage calculation case"]}),
feature("toll-fuel-audit","DCI12","Toll fuel audit","Execute toll fuel audit using drayage contracts, containers, bookings, port and ramp events, appointments, chassis usage, flips, splits, pre-pulls, storage, permits, tolls, invoices, and credits.","Produce a governed toll fuel audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Drayage Carrier / Container","text","Drayage Carrier / Container · Standard Case"],["caseReference","Toll fuel audit Reference","text","DCI12-2026-001"],["billedAmount","Drayage Billed Amount","currency",716000],["supportedAmount","Event-Supported Amount","currency",615760],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Drayage contract library case","Container booking registry case","Port rail event ingestion case","Appointment evidence case","Base drayage calculation case"]}),
feature("failed-attempt-responsibility","DCI13","Failed attempt responsibility","Execute failed attempt responsibility using drayage contracts, containers, bookings, port and ramp events, appointments, chassis usage, flips, splits, pre-pulls, storage, permits, tolls, invoices, and credits.","Produce a governed failed attempt responsibility decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Drayage Carrier / Container","text","Drayage Carrier / Container · Standard Case"],["caseReference","Failed attempt responsibility Reference","text","DCI13-2026-001"],["billedAmount","Drayage Billed Amount","currency",716000],["supportedAmount","Event-Supported Amount","currency",615760],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Drayage contract library case","Container booking registry case","Port rail event ingestion case","Appointment evidence case","Base drayage calculation case"]}),
feature("invoice-recalculation","DCI14","Invoice recalculation","Execute invoice recalculation using drayage contracts, containers, bookings, port and ramp events, appointments, chassis usage, flips, splits, pre-pulls, storage, permits, tolls, invoices, and credits.","Produce a governed invoice recalculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Drayage Carrier / Container","text","Drayage Carrier / Container · Standard Case"],["caseReference","Invoice recalculation Reference","text","DCI14-2026-001"],["billedAmount","Drayage Billed Amount","currency",716000],["supportedAmount","Event-Supported Amount","currency",615760],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Drayage contract library case","Container booking registry case","Port rail event ingestion case","Appointment evidence case","Base drayage calculation case"]}),
feature("port-carrier-analytics","DCI15","Port carrier analytics","Execute port carrier analytics using drayage contracts, containers, bookings, port and ramp events, appointments, chassis usage, flips, splits, pre-pulls, storage, permits, tolls, invoices, and credits.","Produce a governed port carrier analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Drayage Carrier / Container","text","Drayage Carrier / Container · Standard Case"],["caseReference","Port carrier analytics Reference","text","DCI15-2026-001"],["billedAmount","Drayage Billed Amount","currency",716000],["supportedAmount","Event-Supported Amount","currency",615760],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Drayage contract library case","Container booking registry case","Port rail event ingestion case","Appointment evidence case","Base drayage calculation case"]})
]);
